openapi: 3.0.0
info:
  title: VUI Issuer Resolution API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.0
servers:
  - url: https://vui.gataca.io/v1
    description: Gataca's implementor server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /health:
    get:
      summary: Returns if the service is up and running.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: Server UP
  /version:
    get:
      summary: Returns the current version of the service.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: object